# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uuv_plume_msgs/CreateSpheroidPlumeRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class CreateSpheroidPlumeRequest(genpy.Message):
  _md5sum = "db32e79c6acbda79b2d8be3ff5b7d146"
  _type = "uuv_plume_msgs/CreateSpheroidPlumeRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

geometry_msgs/Point source
geometry_msgs/Quaternion orientation
int32 n_points
float32 a
float32 c
float64 x_min
float64 x_max
float64 y_min
float64 y_max
float64 z_min
float64 z_max

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['source','orientation','n_points','a','c','x_min','x_max','y_min','y_max','z_min','z_max']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Quaternion','int32','float32','float32','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       source,orientation,n_points,a,c,x_min,x_max,y_min,y_max,z_min,z_max

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CreateSpheroidPlumeRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.source is None:
        self.source = geometry_msgs.msg.Point()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.n_points is None:
        self.n_points = 0
      if self.a is None:
        self.a = 0.
      if self.c is None:
        self.c = 0.
      if self.x_min is None:
        self.x_min = 0.
      if self.x_max is None:
        self.x_max = 0.
      if self.y_min is None:
        self.y_min = 0.
      if self.y_max is None:
        self.y_max = 0.
      if self.z_min is None:
        self.z_min = 0.
      if self.z_max is None:
        self.z_max = 0.
    else:
      self.source = geometry_msgs.msg.Point()
      self.orientation = geometry_msgs.msg.Quaternion()
      self.n_points = 0
      self.a = 0.
      self.c = 0.
      self.x_min = 0.
      self.x_max = 0.
      self.y_min = 0.
      self.y_max = 0.
      self.z_min = 0.
      self.z_max = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7di2f6d().pack(_x.source.x, _x.source.y, _x.source.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.n_points, _x.a, _x.c, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.source is None:
        self.source = geometry_msgs.msg.Point()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.source.x, _x.source.y, _x.source.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.n_points, _x.a, _x.c, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max,) = _get_struct_7di2f6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7di2f6d().pack(_x.source.x, _x.source.y, _x.source.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.n_points, _x.a, _x.c, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.source is None:
        self.source = geometry_msgs.msg.Point()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.source.x, _x.source.y, _x.source.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.n_points, _x.a, _x.c, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max,) = _get_struct_7di2f6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7di2f6d = None
def _get_struct_7di2f6d():
    global _struct_7di2f6d
    if _struct_7di2f6d is None:
        _struct_7di2f6d = struct.Struct("<7di2f6d")
    return _struct_7di2f6d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uuv_plume_msgs/CreateSpheroidPlumeResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CreateSpheroidPlumeResponse(genpy.Message):
  _md5sum = "358e233cde0c8a8bcfea4ce193f8fc15"
  _type = "uuv_plume_msgs/CreateSpheroidPlumeResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success

"""
  __slots__ = ['success']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CreateSpheroidPlumeResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
    else:
      self.success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class CreateSpheroidPlume(object):
  _type          = 'uuv_plume_msgs/CreateSpheroidPlume'
  _md5sum = '38f854ae91d626d8d19fa91958cef8f9'
  _request_class  = CreateSpheroidPlumeRequest
  _response_class = CreateSpheroidPlumeResponse
