// Generated by gencpp from file uuv_plume_msgs/GetCurrentModel.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_GETCURRENTMODEL_H
#define UUV_PLUME_MSGS_MESSAGE_GETCURRENTMODEL_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/GetCurrentModelRequest.h>
#include <uuv_plume_msgs/GetCurrentModelResponse.h>


namespace uuv_plume_msgs
{

struct GetCurrentModel
{

typedef GetCurrentModelRequest Request;
typedef GetCurrentModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentModel
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::GetCurrentModel > {
  static const char* value()
  {
    return "b8222571af4e4180b9b706d1e17ad7e1";
  }

  static const char* value(const ::uuv_plume_msgs::GetCurrentModel&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::GetCurrentModel > {
  static const char* value()
  {
    return "uuv_plume_msgs/GetCurrentModel";
  }

  static const char* value(const ::uuv_plume_msgs::GetCurrentModel&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::GetCurrentModelRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetCurrentModel >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetCurrentModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetCurrentModel >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetCurrentModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetCurrentModelRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::GetCurrentModel >
template<>
struct DataType< ::uuv_plume_msgs::GetCurrentModelRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetCurrentModel >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetCurrentModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::GetCurrentModelResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetCurrentModel >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetCurrentModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetCurrentModel >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetCurrentModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetCurrentModelResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::GetCurrentModel >
template<>
struct DataType< ::uuv_plume_msgs::GetCurrentModelResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetCurrentModel >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetCurrentModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_GETCURRENTMODEL_H
