// Generated by gencpp from file uuv_plume_msgs/GetNumParticles.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_GETNUMPARTICLES_H
#define UUV_PLUME_MSGS_MESSAGE_GETNUMPARTICLES_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/GetNumParticlesRequest.h>
#include <uuv_plume_msgs/GetNumParticlesResponse.h>


namespace uuv_plume_msgs
{

struct GetNumParticles
{

typedef GetNumParticlesRequest Request;
typedef GetNumParticlesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNumParticles
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::GetNumParticles > {
  static const char* value()
  {
    return "b3e7a05396001d2e02f04b13547a3da2";
  }

  static const char* value(const ::uuv_plume_msgs::GetNumParticles&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::GetNumParticles > {
  static const char* value()
  {
    return "uuv_plume_msgs/GetNumParticles";
  }

  static const char* value(const ::uuv_plume_msgs::GetNumParticles&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::GetNumParticlesRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetNumParticles >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetNumParticlesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetNumParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetNumParticlesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetNumParticlesRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::GetNumParticles >
template<>
struct DataType< ::uuv_plume_msgs::GetNumParticlesRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetNumParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetNumParticlesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::GetNumParticlesResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetNumParticles >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetNumParticlesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetNumParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetNumParticlesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetNumParticlesResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::GetNumParticles >
template<>
struct DataType< ::uuv_plume_msgs::GetNumParticlesResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetNumParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetNumParticlesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_GETNUMPARTICLES_H
