// Generated by gencpp from file uuv_plume_msgs/GetPlumeConfiguration.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_GETPLUMECONFIGURATION_H
#define UUV_PLUME_MSGS_MESSAGE_GETPLUMECONFIGURATION_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/GetPlumeConfigurationRequest.h>
#include <uuv_plume_msgs/GetPlumeConfigurationResponse.h>


namespace uuv_plume_msgs
{

struct GetPlumeConfiguration
{

typedef GetPlumeConfigurationRequest Request;
typedef GetPlumeConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlumeConfiguration
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::GetPlumeConfiguration > {
  static const char* value()
  {
    return "eb1615b61ec9b80c7981906c8ffbab07";
  }

  static const char* value(const ::uuv_plume_msgs::GetPlumeConfiguration&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::GetPlumeConfiguration > {
  static const char* value()
  {
    return "uuv_plume_msgs/GetPlumeConfiguration";
  }

  static const char* value(const ::uuv_plume_msgs::GetPlumeConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeConfigurationRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeConfiguration >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetPlumeConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetPlumeConfiguration >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetPlumeConfigurationRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::GetPlumeConfiguration >
template<>
struct DataType< ::uuv_plume_msgs::GetPlumeConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetPlumeConfiguration >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeConfigurationResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeConfiguration >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetPlumeConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetPlumeConfiguration >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetPlumeConfigurationResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::GetPlumeConfiguration >
template<>
struct DataType< ::uuv_plume_msgs::GetPlumeConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetPlumeConfiguration >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_GETPLUMECONFIGURATION_H
