// Generated by gencpp from file uuv_plume_msgs/SetCurrentDirection.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_SETCURRENTDIRECTION_H
#define UUV_PLUME_MSGS_MESSAGE_SETCURRENTDIRECTION_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/SetCurrentDirectionRequest.h>
#include <uuv_plume_msgs/SetCurrentDirectionResponse.h>


namespace uuv_plume_msgs
{

struct SetCurrentDirection
{

typedef SetCurrentDirectionRequest Request;
typedef SetCurrentDirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCurrentDirection
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::SetCurrentDirection > {
  static const char* value()
  {
    return "c1a76fcaf62dc4534903e93216b59a79";
  }

  static const char* value(const ::uuv_plume_msgs::SetCurrentDirection&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::SetCurrentDirection > {
  static const char* value()
  {
    return "uuv_plume_msgs/SetCurrentDirection";
  }

  static const char* value(const ::uuv_plume_msgs::SetCurrentDirection&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentDirectionRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentDirection >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetCurrentDirectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetCurrentDirection >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentDirectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetCurrentDirectionRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::SetCurrentDirection >
template<>
struct DataType< ::uuv_plume_msgs::SetCurrentDirectionRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetCurrentDirection >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentDirectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentDirectionResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentDirection >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetCurrentDirectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetCurrentDirection >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentDirectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetCurrentDirectionResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::SetCurrentDirection >
template<>
struct DataType< ::uuv_plume_msgs::SetCurrentDirectionResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetCurrentDirection >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentDirectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_SETCURRENTDIRECTION_H
