// Generated by gencpp from file uuv_plume_msgs/SetPlumeLimits.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_SETPLUMELIMITS_H
#define UUV_PLUME_MSGS_MESSAGE_SETPLUMELIMITS_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/SetPlumeLimitsRequest.h>
#include <uuv_plume_msgs/SetPlumeLimitsResponse.h>


namespace uuv_plume_msgs
{

struct SetPlumeLimits
{

typedef SetPlumeLimitsRequest Request;
typedef SetPlumeLimitsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPlumeLimits
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::SetPlumeLimits > {
  static const char* value()
  {
    return "e7030c8a2a5eb00a0d6cf898df109eb8";
  }

  static const char* value(const ::uuv_plume_msgs::SetPlumeLimits&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::SetPlumeLimits > {
  static const char* value()
  {
    return "uuv_plume_msgs/SetPlumeLimits";
  }

  static const char* value(const ::uuv_plume_msgs::SetPlumeLimits&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeLimitsRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeLimits >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetPlumeLimitsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetPlumeLimits >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeLimitsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetPlumeLimitsRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::SetPlumeLimits >
template<>
struct DataType< ::uuv_plume_msgs::SetPlumeLimitsRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetPlumeLimits >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeLimitsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeLimitsResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeLimits >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetPlumeLimitsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetPlumeLimits >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeLimitsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetPlumeLimitsResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::SetPlumeLimits >
template<>
struct DataType< ::uuv_plume_msgs::SetPlumeLimitsResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetPlumeLimits >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeLimitsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_SETPLUMELIMITS_H
