// Generated by gencpp from file uuv_plume_msgs/StorePlumeStateRequest.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATEREQUEST_H
#define UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uuv_plume_msgs
{
template <class ContainerAllocator>
struct StorePlumeStateRequest_
{
  typedef StorePlumeStateRequest_<ContainerAllocator> Type;

  StorePlumeStateRequest_()
    : output_dir()
    , filename()  {
    }
  StorePlumeStateRequest_(const ContainerAllocator& _alloc)
    : output_dir(_alloc)
    , filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_dir_type;
  _output_dir_type output_dir;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StorePlumeStateRequest_

typedef ::uuv_plume_msgs::StorePlumeStateRequest_<std::allocator<void> > StorePlumeStateRequest;

typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateRequest > StorePlumeStateRequestPtr;
typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateRequest const> StorePlumeStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator1> & lhs, const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.output_dir == rhs.output_dir &&
    lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator1> & lhs, const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_plume_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "808e933d49d59744bb06ce71ae0bb8f3";
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x808e933d49d59744ULL;
  static const uint64_t static_value2 = 0xbb06ce71ae0bb8f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_plume_msgs/StorePlumeStateRequest";
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"string output_dir\n"
"string filename\n"
;
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_dir);
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StorePlumeStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_plume_msgs::StorePlumeStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "output_dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output_dir);
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATEREQUEST_H
