// Generated by gencpp from file uuv_plume_msgs/CreatePassiveScalarTurbulentPlumeRequest.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_CREATEPASSIVESCALARTURBULENTPLUMEREQUEST_H
#define UUV_PLUME_MSGS_MESSAGE_CREATEPASSIVESCALARTURBULENTPLUMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace uuv_plume_msgs
{
template <class ContainerAllocator>
struct CreatePassiveScalarTurbulentPlumeRequest_
{
  typedef CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> Type;

  CreatePassiveScalarTurbulentPlumeRequest_()
    : turbulent_diffusion_coefficients()
    , source()
    , buoyancy_flux(0.0)
    , stability_param(0.0)
    , n_points(0)
    , max_particles_per_iter(0)
    , x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)
    , max_life_time(0.0)  {
    }
  CreatePassiveScalarTurbulentPlumeRequest_(const ContainerAllocator& _alloc)
    : turbulent_diffusion_coefficients(_alloc)
    , source(_alloc)
    , buoyancy_flux(0.0)
    , stability_param(0.0)
    , n_points(0)
    , max_particles_per_iter(0)
    , x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)
    , max_life_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _turbulent_diffusion_coefficients_type;
  _turbulent_diffusion_coefficients_type turbulent_diffusion_coefficients;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _source_type;
  _source_type source;

   typedef double _buoyancy_flux_type;
  _buoyancy_flux_type buoyancy_flux;

   typedef double _stability_param_type;
  _stability_param_type stability_param;

   typedef int32_t _n_points_type;
  _n_points_type n_points;

   typedef int32_t _max_particles_per_iter_type;
  _max_particles_per_iter_type max_particles_per_iter;

   typedef double _x_min_type;
  _x_min_type x_min;

   typedef double _x_max_type;
  _x_max_type x_max;

   typedef double _y_min_type;
  _y_min_type y_min;

   typedef double _y_max_type;
  _y_max_type y_max;

   typedef double _z_min_type;
  _z_min_type z_min;

   typedef double _z_max_type;
  _z_max_type z_max;

   typedef double _max_life_time_type;
  _max_life_time_type max_life_time;





  typedef boost::shared_ptr< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CreatePassiveScalarTurbulentPlumeRequest_

typedef ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<std::allocator<void> > CreatePassiveScalarTurbulentPlumeRequest;

typedef boost::shared_ptr< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest > CreatePassiveScalarTurbulentPlumeRequestPtr;
typedef boost::shared_ptr< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest const> CreatePassiveScalarTurbulentPlumeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator1> & lhs, const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.turbulent_diffusion_coefficients == rhs.turbulent_diffusion_coefficients &&
    lhs.source == rhs.source &&
    lhs.buoyancy_flux == rhs.buoyancy_flux &&
    lhs.stability_param == rhs.stability_param &&
    lhs.n_points == rhs.n_points &&
    lhs.max_particles_per_iter == rhs.max_particles_per_iter &&
    lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max &&
    lhs.z_min == rhs.z_min &&
    lhs.z_max == rhs.z_max &&
    lhs.max_life_time == rhs.max_life_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator1> & lhs, const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_plume_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1ed1b318bcdeacf878e86ddcf7ed2c";
  }

  static const char* value(const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1ed1b318bcdeacULL;
  static const uint64_t static_value2 = 0xf878e86ddcf7ed2cULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_plume_msgs/CreatePassiveScalarTurbulentPlumeRequest";
  }

  static const char* value(const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"geometry_msgs/Vector3 turbulent_diffusion_coefficients\n"
"geometry_msgs/Point source\n"
"float64 buoyancy_flux\n"
"float64 stability_param\n"
"int32 n_points\n"
"int32 max_particles_per_iter\n"
"float64 x_min\n"
"float64 x_max\n"
"float64 y_min\n"
"float64 y_max\n"
"float64 z_min\n"
"float64 z_max\n"
"float64 max_life_time\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turbulent_diffusion_coefficients);
      stream.next(m.source);
      stream.next(m.buoyancy_flux);
      stream.next(m.stability_param);
      stream.next(m.n_points);
      stream.next(m.max_particles_per_iter);
      stream.next(m.x_min);
      stream.next(m.x_max);
      stream.next(m.y_min);
      stream.next(m.y_max);
      stream.next(m.z_min);
      stream.next(m.z_max);
      stream.next(m.max_life_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreatePassiveScalarTurbulentPlumeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_plume_msgs::CreatePassiveScalarTurbulentPlumeRequest_<ContainerAllocator>& v)
  {
    s << indent << "turbulent_diffusion_coefficients: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.turbulent_diffusion_coefficients);
    s << indent << "source: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.source);
    s << indent << "buoyancy_flux: ";
    Printer<double>::stream(s, indent + "  ", v.buoyancy_flux);
    s << indent << "stability_param: ";
    Printer<double>::stream(s, indent + "  ", v.stability_param);
    s << indent << "n_points: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_points);
    s << indent << "max_particles_per_iter: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_particles_per_iter);
    s << indent << "x_min: ";
    Printer<double>::stream(s, indent + "  ", v.x_min);
    s << indent << "x_max: ";
    Printer<double>::stream(s, indent + "  ", v.x_max);
    s << indent << "y_min: ";
    Printer<double>::stream(s, indent + "  ", v.y_min);
    s << indent << "y_max: ";
    Printer<double>::stream(s, indent + "  ", v.y_max);
    s << indent << "z_min: ";
    Printer<double>::stream(s, indent + "  ", v.z_min);
    s << indent << "z_max: ";
    Printer<double>::stream(s, indent + "  ", v.z_max);
    s << indent << "max_life_time: ";
    Printer<double>::stream(s, indent + "  ", v.max_life_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_CREATEPASSIVESCALARTURBULENTPLUMEREQUEST_H
