// Generated by gencpp from file uuv_plume_msgs/GetPlumeSourcePosition.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_GETPLUMESOURCEPOSITION_H
#define UUV_PLUME_MSGS_MESSAGE_GETPLUMESOURCEPOSITION_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/GetPlumeSourcePositionRequest.h>
#include <uuv_plume_msgs/GetPlumeSourcePositionResponse.h>


namespace uuv_plume_msgs
{

struct GetPlumeSourcePosition
{

typedef GetPlumeSourcePositionRequest Request;
typedef GetPlumeSourcePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlumeSourcePosition
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePosition > {
  static const char* value()
  {
    return "74e696b4bb2fd623e3aef7e08928baee";
  }

  static const char* value(const ::uuv_plume_msgs::GetPlumeSourcePosition&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::GetPlumeSourcePosition > {
  static const char* value()
  {
    return "uuv_plume_msgs/GetPlumeSourcePosition";
  }

  static const char* value(const ::uuv_plume_msgs::GetPlumeSourcePosition&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePositionRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePosition >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeSourcePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetPlumeSourcePositionRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::GetPlumeSourcePosition >
template<>
struct DataType< ::uuv_plume_msgs::GetPlumeSourcePositionRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeSourcePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePositionResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePosition >
template<>
struct MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::GetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeSourcePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::GetPlumeSourcePositionResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::GetPlumeSourcePosition >
template<>
struct DataType< ::uuv_plume_msgs::GetPlumeSourcePositionResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::GetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::GetPlumeSourcePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_GETPLUMESOURCEPOSITION_H
