// Generated by gencpp from file uuv_plume_msgs/LoadPlumeParticles.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_LOADPLUMEPARTICLES_H
#define UUV_PLUME_MSGS_MESSAGE_LOADPLUMEPARTICLES_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/LoadPlumeParticlesRequest.h>
#include <uuv_plume_msgs/LoadPlumeParticlesResponse.h>


namespace uuv_plume_msgs
{

struct LoadPlumeParticles
{

typedef LoadPlumeParticlesRequest Request;
typedef LoadPlumeParticlesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadPlumeParticles
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::LoadPlumeParticles > {
  static const char* value()
  {
    return "89cea82104ad560d0ae7df2662f9b983";
  }

  static const char* value(const ::uuv_plume_msgs::LoadPlumeParticles&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::LoadPlumeParticles > {
  static const char* value()
  {
    return "uuv_plume_msgs/LoadPlumeParticles";
  }

  static const char* value(const ::uuv_plume_msgs::LoadPlumeParticles&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::LoadPlumeParticlesRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::LoadPlumeParticles >
template<>
struct MD5Sum< ::uuv_plume_msgs::LoadPlumeParticlesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::LoadPlumeParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::LoadPlumeParticlesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::LoadPlumeParticlesRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::LoadPlumeParticles >
template<>
struct DataType< ::uuv_plume_msgs::LoadPlumeParticlesRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::LoadPlumeParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::LoadPlumeParticlesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::LoadPlumeParticlesResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::LoadPlumeParticles >
template<>
struct MD5Sum< ::uuv_plume_msgs::LoadPlumeParticlesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::LoadPlumeParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::LoadPlumeParticlesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::LoadPlumeParticlesResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::LoadPlumeParticles >
template<>
struct DataType< ::uuv_plume_msgs::LoadPlumeParticlesResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::LoadPlumeParticles >::value();
  }
  static const char* value(const ::uuv_plume_msgs::LoadPlumeParticlesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_LOADPLUMEPARTICLES_H
