// Generated by gencpp from file uuv_plume_msgs/SetCurrentVelocity.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_SETCURRENTVELOCITY_H
#define UUV_PLUME_MSGS_MESSAGE_SETCURRENTVELOCITY_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/SetCurrentVelocityRequest.h>
#include <uuv_plume_msgs/SetCurrentVelocityResponse.h>


namespace uuv_plume_msgs
{

struct SetCurrentVelocity
{

typedef SetCurrentVelocityRequest Request;
typedef SetCurrentVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCurrentVelocity
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::SetCurrentVelocity > {
  static const char* value()
  {
    return "29979ce59631380ff17a987b6ff491eb";
  }

  static const char* value(const ::uuv_plume_msgs::SetCurrentVelocity&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::SetCurrentVelocity > {
  static const char* value()
  {
    return "uuv_plume_msgs/SetCurrentVelocity";
  }

  static const char* value(const ::uuv_plume_msgs::SetCurrentVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentVelocityRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentVelocity >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetCurrentVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetCurrentVelocity >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetCurrentVelocityRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::SetCurrentVelocity >
template<>
struct DataType< ::uuv_plume_msgs::SetCurrentVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetCurrentVelocity >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentVelocityResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetCurrentVelocity >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetCurrentVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetCurrentVelocity >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetCurrentVelocityResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::SetCurrentVelocity >
template<>
struct DataType< ::uuv_plume_msgs::SetCurrentVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetCurrentVelocity >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetCurrentVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_SETCURRENTVELOCITY_H
