// Generated by gencpp from file uuv_plume_msgs/SetPlumeSourcePosition.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_SETPLUMESOURCEPOSITION_H
#define UUV_PLUME_MSGS_MESSAGE_SETPLUMESOURCEPOSITION_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/SetPlumeSourcePositionRequest.h>
#include <uuv_plume_msgs/SetPlumeSourcePositionResponse.h>


namespace uuv_plume_msgs
{

struct SetPlumeSourcePosition
{

typedef SetPlumeSourcePositionRequest Request;
typedef SetPlumeSourcePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPlumeSourcePosition
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePosition > {
  static const char* value()
  {
    return "6f914c566d493481f609db28b34106cb";
  }

  static const char* value(const ::uuv_plume_msgs::SetPlumeSourcePosition&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::SetPlumeSourcePosition > {
  static const char* value()
  {
    return "uuv_plume_msgs/SetPlumeSourcePosition";
  }

  static const char* value(const ::uuv_plume_msgs::SetPlumeSourcePosition&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePositionRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePosition >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeSourcePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetPlumeSourcePositionRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::SetPlumeSourcePosition >
template<>
struct DataType< ::uuv_plume_msgs::SetPlumeSourcePositionRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeSourcePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePositionResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePosition >
template<>
struct MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::SetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeSourcePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::SetPlumeSourcePositionResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::SetPlumeSourcePosition >
template<>
struct DataType< ::uuv_plume_msgs::SetPlumeSourcePositionResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::SetPlumeSourcePosition >::value();
  }
  static const char* value(const ::uuv_plume_msgs::SetPlumeSourcePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_SETPLUMESOURCEPOSITION_H
