// Generated by gencpp from file uuv_plume_msgs/StorePlumeStateResponse.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATERESPONSE_H
#define UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uuv_plume_msgs
{
template <class ContainerAllocator>
struct StorePlumeStateResponse_
{
  typedef StorePlumeStateResponse_<ContainerAllocator> Type;

  StorePlumeStateResponse_()
    : success(false)
    , plume_file()  {
    }
  StorePlumeStateResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , plume_file(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plume_file_type;
  _plume_file_type plume_file;





  typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StorePlumeStateResponse_

typedef ::uuv_plume_msgs::StorePlumeStateResponse_<std::allocator<void> > StorePlumeStateResponse;

typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateResponse > StorePlumeStateResponsePtr;
typedef boost::shared_ptr< ::uuv_plume_msgs::StorePlumeStateResponse const> StorePlumeStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator1> & lhs, const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.plume_file == rhs.plume_file;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator1> & lhs, const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_plume_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc8ae3d15235b49c122723db29550c50";
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc8ae3d15235b49cULL;
  static const uint64_t static_value2 = 0x122723db29550c50ULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_plume_msgs/StorePlumeStateResponse";
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string plume_file\n"
;
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.plume_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StorePlumeStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_plume_msgs::StorePlumeStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "plume_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plume_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATERESPONSE_H
