// Generated by gencpp from file uuv_plume_msgs/StorePlumeState.msg
// DO NOT EDIT!


#ifndef UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATE_H
#define UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATE_H

#include <ros/service_traits.h>


#include <uuv_plume_msgs/StorePlumeStateRequest.h>
#include <uuv_plume_msgs/StorePlumeStateResponse.h>


namespace uuv_plume_msgs
{

struct StorePlumeState
{

typedef StorePlumeStateRequest Request;
typedef StorePlumeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StorePlumeState
} // namespace uuv_plume_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_plume_msgs::StorePlumeState > {
  static const char* value()
  {
    return "4fbc4c340238072a838f039245e40b09";
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeState&) { return value(); }
};

template<>
struct DataType< ::uuv_plume_msgs::StorePlumeState > {
  static const char* value()
  {
    return "uuv_plume_msgs/StorePlumeState";
  }

  static const char* value(const ::uuv_plume_msgs::StorePlumeState&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_plume_msgs::StorePlumeStateRequest> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::StorePlumeState >
template<>
struct MD5Sum< ::uuv_plume_msgs::StorePlumeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::StorePlumeState >::value();
  }
  static const char* value(const ::uuv_plume_msgs::StorePlumeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::StorePlumeStateRequest> should match
// service_traits::DataType< ::uuv_plume_msgs::StorePlumeState >
template<>
struct DataType< ::uuv_plume_msgs::StorePlumeStateRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::StorePlumeState >::value();
  }
  static const char* value(const ::uuv_plume_msgs::StorePlumeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_plume_msgs::StorePlumeStateResponse> should match
// service_traits::MD5Sum< ::uuv_plume_msgs::StorePlumeState >
template<>
struct MD5Sum< ::uuv_plume_msgs::StorePlumeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_plume_msgs::StorePlumeState >::value();
  }
  static const char* value(const ::uuv_plume_msgs::StorePlumeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_plume_msgs::StorePlumeStateResponse> should match
// service_traits::DataType< ::uuv_plume_msgs::StorePlumeState >
template<>
struct DataType< ::uuv_plume_msgs::StorePlumeStateResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_plume_msgs::StorePlumeState >::value();
  }
  static const char* value(const ::uuv_plume_msgs::StorePlumeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PLUME_MSGS_MESSAGE_STOREPLUMESTATE_H
