// Generated by gencpp from file ros_services/ConcentrationValueRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_CONCENTRATIONVALUEREQUEST_H
#define ROS_SERVICES_MESSAGE_CONCENTRATIONVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_services
{
template <class ContainerAllocator>
struct ConcentrationValueRequest_
{
  typedef ConcentrationValueRequest_<ContainerAllocator> Type;

  ConcentrationValueRequest_()
    : current_concentration_c(0.0)  {
    }
  ConcentrationValueRequest_(const ContainerAllocator& _alloc)
    : current_concentration_c(0.0)  {
  (void)_alloc;
    }



   typedef double _current_concentration_c_type;
  _current_concentration_c_type current_concentration_c;





  typedef boost::shared_ptr< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConcentrationValueRequest_

typedef ::ros_services::ConcentrationValueRequest_<std::allocator<void> > ConcentrationValueRequest;

typedef boost::shared_ptr< ::ros_services::ConcentrationValueRequest > ConcentrationValueRequestPtr;
typedef boost::shared_ptr< ::ros_services::ConcentrationValueRequest const> ConcentrationValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_services::ConcentrationValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_services::ConcentrationValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::ConcentrationValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.current_concentration_c == rhs.current_concentration_c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_services::ConcentrationValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::ConcentrationValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b359ca613257eee99e18b9299b68b3d5";
  }

  static const char* value(const ::ros_services::ConcentrationValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb359ca613257eee9ULL;
  static const uint64_t static_value2 = 0x9e18b9299b68b3d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_services/ConcentrationValueRequest";
  }

  static const char* value(const ::ros_services::ConcentrationValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 current_concentration_c\n"
;
  }

  static const char* value(const ::ros_services::ConcentrationValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_concentration_c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConcentrationValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_services::ConcentrationValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_services::ConcentrationValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "current_concentration_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_concentration_c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_CONCENTRATIONVALUEREQUEST_H
