// Generated by gencpp from file ros_services/ImuValueRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_IMUVALUEREQUEST_H
#define ROS_SERVICES_MESSAGE_IMUVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_services
{
template <class ContainerAllocator>
struct ImuValueRequest_
{
  typedef ImuValueRequest_<ContainerAllocator> Type;

  ImuValueRequest_()
    : current_x_orientation_c(0.0)
    , current_y_orientation_c(0.0)
    , current_z_orientation_c(0.0)
    , current_w_orientation_c(0.0)
    , current_x_angular_velocity_c(0.0)
    , current_y_angular_velocity_c(0.0)
    , current_z_angular_velocity_c(0.0)
    , current_x_linear_acceleration_c(0.0)
    , current_y_linear_acceleration_c(0.0)
    , current_z_linear_acceleration_c(0.0)  {
    }
  ImuValueRequest_(const ContainerAllocator& _alloc)
    : current_x_orientation_c(0.0)
    , current_y_orientation_c(0.0)
    , current_z_orientation_c(0.0)
    , current_w_orientation_c(0.0)
    , current_x_angular_velocity_c(0.0)
    , current_y_angular_velocity_c(0.0)
    , current_z_angular_velocity_c(0.0)
    , current_x_linear_acceleration_c(0.0)
    , current_y_linear_acceleration_c(0.0)
    , current_z_linear_acceleration_c(0.0)  {
  (void)_alloc;
    }



   typedef double _current_x_orientation_c_type;
  _current_x_orientation_c_type current_x_orientation_c;

   typedef double _current_y_orientation_c_type;
  _current_y_orientation_c_type current_y_orientation_c;

   typedef double _current_z_orientation_c_type;
  _current_z_orientation_c_type current_z_orientation_c;

   typedef double _current_w_orientation_c_type;
  _current_w_orientation_c_type current_w_orientation_c;

   typedef double _current_x_angular_velocity_c_type;
  _current_x_angular_velocity_c_type current_x_angular_velocity_c;

   typedef double _current_y_angular_velocity_c_type;
  _current_y_angular_velocity_c_type current_y_angular_velocity_c;

   typedef double _current_z_angular_velocity_c_type;
  _current_z_angular_velocity_c_type current_z_angular_velocity_c;

   typedef double _current_x_linear_acceleration_c_type;
  _current_x_linear_acceleration_c_type current_x_linear_acceleration_c;

   typedef double _current_y_linear_acceleration_c_type;
  _current_y_linear_acceleration_c_type current_y_linear_acceleration_c;

   typedef double _current_z_linear_acceleration_c_type;
  _current_z_linear_acceleration_c_type current_z_linear_acceleration_c;





  typedef boost::shared_ptr< ::ros_services::ImuValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_services::ImuValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImuValueRequest_

typedef ::ros_services::ImuValueRequest_<std::allocator<void> > ImuValueRequest;

typedef boost::shared_ptr< ::ros_services::ImuValueRequest > ImuValueRequestPtr;
typedef boost::shared_ptr< ::ros_services::ImuValueRequest const> ImuValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_services::ImuValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_services::ImuValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_services::ImuValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::ImuValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.current_x_orientation_c == rhs.current_x_orientation_c &&
    lhs.current_y_orientation_c == rhs.current_y_orientation_c &&
    lhs.current_z_orientation_c == rhs.current_z_orientation_c &&
    lhs.current_w_orientation_c == rhs.current_w_orientation_c &&
    lhs.current_x_angular_velocity_c == rhs.current_x_angular_velocity_c &&
    lhs.current_y_angular_velocity_c == rhs.current_y_angular_velocity_c &&
    lhs.current_z_angular_velocity_c == rhs.current_z_angular_velocity_c &&
    lhs.current_x_linear_acceleration_c == rhs.current_x_linear_acceleration_c &&
    lhs.current_y_linear_acceleration_c == rhs.current_y_linear_acceleration_c &&
    lhs.current_z_linear_acceleration_c == rhs.current_z_linear_acceleration_c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_services::ImuValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::ImuValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::ImuValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::ImuValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::ImuValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::ImuValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::ImuValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::ImuValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_services::ImuValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba80b4a22f2f77611473d2d4f470fb77";
  }

  static const char* value(const ::ros_services::ImuValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba80b4a22f2f7761ULL;
  static const uint64_t static_value2 = 0x1473d2d4f470fb77ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_services::ImuValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_services/ImuValueRequest";
  }

  static const char* value(const ::ros_services::ImuValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_services::ImuValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 current_x_orientation_c\n"
"float64 current_y_orientation_c\n"
"float64 current_z_orientation_c\n"
"float64 current_w_orientation_c\n"
"float64 current_x_angular_velocity_c\n"
"float64 current_y_angular_velocity_c\n"
"float64 current_z_angular_velocity_c\n"
"float64 current_x_linear_acceleration_c\n"
"float64 current_y_linear_acceleration_c\n"
"float64 current_z_linear_acceleration_c\n"
;
  }

  static const char* value(const ::ros_services::ImuValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_services::ImuValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_x_orientation_c);
      stream.next(m.current_y_orientation_c);
      stream.next(m.current_z_orientation_c);
      stream.next(m.current_w_orientation_c);
      stream.next(m.current_x_angular_velocity_c);
      stream.next(m.current_y_angular_velocity_c);
      stream.next(m.current_z_angular_velocity_c);
      stream.next(m.current_x_linear_acceleration_c);
      stream.next(m.current_y_linear_acceleration_c);
      stream.next(m.current_z_linear_acceleration_c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_services::ImuValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_services::ImuValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "current_x_orientation_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_x_orientation_c);
    s << indent << "current_y_orientation_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_y_orientation_c);
    s << indent << "current_z_orientation_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_z_orientation_c);
    s << indent << "current_w_orientation_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_w_orientation_c);
    s << indent << "current_x_angular_velocity_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_x_angular_velocity_c);
    s << indent << "current_y_angular_velocity_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_y_angular_velocity_c);
    s << indent << "current_z_angular_velocity_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_z_angular_velocity_c);
    s << indent << "current_x_linear_acceleration_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_x_linear_acceleration_c);
    s << indent << "current_y_linear_acceleration_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_y_linear_acceleration_c);
    s << indent << "current_z_linear_acceleration_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_z_linear_acceleration_c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_IMUVALUEREQUEST_H
