// Generated by gencpp from file ros_services/PressureValueRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_PRESSUREVALUEREQUEST_H
#define ROS_SERVICES_MESSAGE_PRESSUREVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_services
{
template <class ContainerAllocator>
struct PressureValueRequest_
{
  typedef PressureValueRequest_<ContainerAllocator> Type;

  PressureValueRequest_()
    : current_pressure_c(0.0)  {
    }
  PressureValueRequest_(const ContainerAllocator& _alloc)
    : current_pressure_c(0.0)  {
  (void)_alloc;
    }



   typedef double _current_pressure_c_type;
  _current_pressure_c_type current_pressure_c;





  typedef boost::shared_ptr< ::ros_services::PressureValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_services::PressureValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PressureValueRequest_

typedef ::ros_services::PressureValueRequest_<std::allocator<void> > PressureValueRequest;

typedef boost::shared_ptr< ::ros_services::PressureValueRequest > PressureValueRequestPtr;
typedef boost::shared_ptr< ::ros_services::PressureValueRequest const> PressureValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_services::PressureValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_services::PressureValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_services::PressureValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::PressureValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.current_pressure_c == rhs.current_pressure_c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_services::PressureValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::PressureValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::PressureValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::PressureValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::PressureValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::PressureValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::PressureValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::PressureValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_services::PressureValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "052020c23f0980f9b0951ce4ec778a17";
  }

  static const char* value(const ::ros_services::PressureValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x052020c23f0980f9ULL;
  static const uint64_t static_value2 = 0xb0951ce4ec778a17ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_services::PressureValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_services/PressureValueRequest";
  }

  static const char* value(const ::ros_services::PressureValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_services::PressureValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 current_pressure_c\n"
;
  }

  static const char* value(const ::ros_services::PressureValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_services::PressureValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_pressure_c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PressureValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_services::PressureValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_services::PressureValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "current_pressure_c: ";
    Printer<double>::stream(s, indent + "  ", v.current_pressure_c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_PRESSUREVALUEREQUEST_H
