// Generated by gencpp from file ros_services/SonarValueRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_SONARVALUEREQUEST_H
#define ROS_SERVICES_MESSAGE_SONARVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_services
{
template <class ContainerAllocator>
struct SonarValueRequest_
{
  typedef SonarValueRequest_<ContainerAllocator> Type;

  SonarValueRequest_()
    : current_angle_min_c(0.0)
    , current_angle_max_c(0.0)
    , current_angle_increment_c(0.0)
    , current_time_increment_c(0.0)
    , current_scan_time_c(0.0)
    , current_range_min_c(0.0)
    , current_range_max_c(0.0)  {
    }
  SonarValueRequest_(const ContainerAllocator& _alloc)
    : current_angle_min_c(0.0)
    , current_angle_max_c(0.0)
    , current_angle_increment_c(0.0)
    , current_time_increment_c(0.0)
    , current_scan_time_c(0.0)
    , current_range_min_c(0.0)
    , current_range_max_c(0.0)  {
  (void)_alloc;
    }



   typedef float _current_angle_min_c_type;
  _current_angle_min_c_type current_angle_min_c;

   typedef float _current_angle_max_c_type;
  _current_angle_max_c_type current_angle_max_c;

   typedef float _current_angle_increment_c_type;
  _current_angle_increment_c_type current_angle_increment_c;

   typedef float _current_time_increment_c_type;
  _current_time_increment_c_type current_time_increment_c;

   typedef float _current_scan_time_c_type;
  _current_scan_time_c_type current_scan_time_c;

   typedef float _current_range_min_c_type;
  _current_range_min_c_type current_range_min_c;

   typedef float _current_range_max_c_type;
  _current_range_max_c_type current_range_max_c;





  typedef boost::shared_ptr< ::ros_services::SonarValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_services::SonarValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SonarValueRequest_

typedef ::ros_services::SonarValueRequest_<std::allocator<void> > SonarValueRequest;

typedef boost::shared_ptr< ::ros_services::SonarValueRequest > SonarValueRequestPtr;
typedef boost::shared_ptr< ::ros_services::SonarValueRequest const> SonarValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_services::SonarValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_services::SonarValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_services::SonarValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::SonarValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.current_angle_min_c == rhs.current_angle_min_c &&
    lhs.current_angle_max_c == rhs.current_angle_max_c &&
    lhs.current_angle_increment_c == rhs.current_angle_increment_c &&
    lhs.current_time_increment_c == rhs.current_time_increment_c &&
    lhs.current_scan_time_c == rhs.current_scan_time_c &&
    lhs.current_range_min_c == rhs.current_range_min_c &&
    lhs.current_range_max_c == rhs.current_range_max_c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_services::SonarValueRequest_<ContainerAllocator1> & lhs, const ::ros_services::SonarValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::SonarValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_services::SonarValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::SonarValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_services::SonarValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::SonarValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_services::SonarValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_services::SonarValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "172a968124eb1818322b971abb516fef";
  }

  static const char* value(const ::ros_services::SonarValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x172a968124eb1818ULL;
  static const uint64_t static_value2 = 0x322b971abb516fefULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_services::SonarValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_services/SonarValueRequest";
  }

  static const char* value(const ::ros_services::SonarValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_services::SonarValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 current_angle_min_c\n"
"float32 current_angle_max_c\n"
"float32 current_angle_increment_c\n"
"float32 current_time_increment_c\n"
"float32 current_scan_time_c\n"
"float32 current_range_min_c\n"
"float32 current_range_max_c\n"
;
  }

  static const char* value(const ::ros_services::SonarValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_services::SonarValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_angle_min_c);
      stream.next(m.current_angle_max_c);
      stream.next(m.current_angle_increment_c);
      stream.next(m.current_time_increment_c);
      stream.next(m.current_scan_time_c);
      stream.next(m.current_range_min_c);
      stream.next(m.current_range_max_c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonarValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_services::SonarValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_services::SonarValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "current_angle_min_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_angle_min_c);
    s << indent << "current_angle_max_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_angle_max_c);
    s << indent << "current_angle_increment_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_angle_increment_c);
    s << indent << "current_time_increment_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_time_increment_c);
    s << indent << "current_scan_time_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_scan_time_c);
    s << indent << "current_range_min_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_range_min_c);
    s << indent << "current_range_max_c: ";
    Printer<float>::stream(s, indent + "  ", v.current_range_max_c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_SONARVALUEREQUEST_H
