(cl:in-package uuv_plume_msgs-srv)
(cl:export '(TURBULENT_DIFFUSION_COEFFICIENTS-VAL
          TURBULENT_DIFFUSION_COEFFICIENTS
          SOURCE-VAL
          SOURCE
          BUOYANCY_FLUX-VAL
          BUOYANCY_FLUX
          STABILITY_PARAM-VAL
          STABILITY_PARAM
          N_POINTS-VAL
          N_POINTS
          MAX_PARTICLES_PER_ITER-VAL
          MAX_PARTICLES_PER_ITER
          X_MIN-VAL
          X_MIN
          X_MAX-VAL
          X_MAX
          Y_MIN-VAL
          Y_MIN
          Y_MAX-VAL
          Y_MAX
          Z_MIN-VAL
          Z_MIN
          Z_MAX-VAL
          Z_MAX
          MAX_LIFE_TIME-VAL
          MAX_LIFE_TIME
          SUCCESS-VAL
          SUCCESS
))