// Generated by gencpp from file ros_services/ConcentrationValue.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_CONCENTRATIONVALUE_H
#define ROS_SERVICES_MESSAGE_CONCENTRATIONVALUE_H

#include <ros/service_traits.h>


#include <ros_services/ConcentrationValueRequest.h>
#include <ros_services/ConcentrationValueResponse.h>


namespace ros_services
{

struct ConcentrationValue
{

typedef ConcentrationValueRequest Request;
typedef ConcentrationValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConcentrationValue
} // namespace ros_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_services::ConcentrationValue > {
  static const char* value()
  {
    return "8333b5c9fbed73738e837cc4d210323f";
  }

  static const char* value(const ::ros_services::ConcentrationValue&) { return value(); }
};

template<>
struct DataType< ::ros_services::ConcentrationValue > {
  static const char* value()
  {
    return "ros_services/ConcentrationValue";
  }

  static const char* value(const ::ros_services::ConcentrationValue&) { return value(); }
};


// service_traits::MD5Sum< ::ros_services::ConcentrationValueRequest> should match
// service_traits::MD5Sum< ::ros_services::ConcentrationValue >
template<>
struct MD5Sum< ::ros_services::ConcentrationValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::ConcentrationValue >::value();
  }
  static const char* value(const ::ros_services::ConcentrationValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::ConcentrationValueRequest> should match
// service_traits::DataType< ::ros_services::ConcentrationValue >
template<>
struct DataType< ::ros_services::ConcentrationValueRequest>
{
  static const char* value()
  {
    return DataType< ::ros_services::ConcentrationValue >::value();
  }
  static const char* value(const ::ros_services::ConcentrationValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_services::ConcentrationValueResponse> should match
// service_traits::MD5Sum< ::ros_services::ConcentrationValue >
template<>
struct MD5Sum< ::ros_services::ConcentrationValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::ConcentrationValue >::value();
  }
  static const char* value(const ::ros_services::ConcentrationValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::ConcentrationValueResponse> should match
// service_traits::DataType< ::ros_services::ConcentrationValue >
template<>
struct DataType< ::ros_services::ConcentrationValueResponse>
{
  static const char* value()
  {
    return DataType< ::ros_services::ConcentrationValue >::value();
  }
  static const char* value(const ::ros_services::ConcentrationValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_CONCENTRATIONVALUE_H
