// Generated by gencpp from file ros_services/ImuValue.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_IMUVALUE_H
#define ROS_SERVICES_MESSAGE_IMUVALUE_H

#include <ros/service_traits.h>


#include <ros_services/ImuValueRequest.h>
#include <ros_services/ImuValueResponse.h>


namespace ros_services
{

struct ImuValue
{

typedef ImuValueRequest Request;
typedef ImuValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuValue
} // namespace ros_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_services::ImuValue > {
  static const char* value()
  {
    return "d594bb3c4eeaf0325c0b0e4feeca4c15";
  }

  static const char* value(const ::ros_services::ImuValue&) { return value(); }
};

template<>
struct DataType< ::ros_services::ImuValue > {
  static const char* value()
  {
    return "ros_services/ImuValue";
  }

  static const char* value(const ::ros_services::ImuValue&) { return value(); }
};


// service_traits::MD5Sum< ::ros_services::ImuValueRequest> should match
// service_traits::MD5Sum< ::ros_services::ImuValue >
template<>
struct MD5Sum< ::ros_services::ImuValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::ImuValue >::value();
  }
  static const char* value(const ::ros_services::ImuValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::ImuValueRequest> should match
// service_traits::DataType< ::ros_services::ImuValue >
template<>
struct DataType< ::ros_services::ImuValueRequest>
{
  static const char* value()
  {
    return DataType< ::ros_services::ImuValue >::value();
  }
  static const char* value(const ::ros_services::ImuValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_services::ImuValueResponse> should match
// service_traits::MD5Sum< ::ros_services::ImuValue >
template<>
struct MD5Sum< ::ros_services::ImuValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::ImuValue >::value();
  }
  static const char* value(const ::ros_services::ImuValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::ImuValueResponse> should match
// service_traits::DataType< ::ros_services::ImuValue >
template<>
struct DataType< ::ros_services::ImuValueResponse>
{
  static const char* value()
  {
    return DataType< ::ros_services::ImuValue >::value();
  }
  static const char* value(const ::ros_services::ImuValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_IMUVALUE_H
