// Generated by gencpp from file ros_services/PressureValue.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_PRESSUREVALUE_H
#define ROS_SERVICES_MESSAGE_PRESSUREVALUE_H

#include <ros/service_traits.h>


#include <ros_services/PressureValueRequest.h>
#include <ros_services/PressureValueResponse.h>


namespace ros_services
{

struct PressureValue
{

typedef PressureValueRequest Request;
typedef PressureValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PressureValue
} // namespace ros_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_services::PressureValue > {
  static const char* value()
  {
    return "63d5115cef5af2fe80e52603ff8267f0";
  }

  static const char* value(const ::ros_services::PressureValue&) { return value(); }
};

template<>
struct DataType< ::ros_services::PressureValue > {
  static const char* value()
  {
    return "ros_services/PressureValue";
  }

  static const char* value(const ::ros_services::PressureValue&) { return value(); }
};


// service_traits::MD5Sum< ::ros_services::PressureValueRequest> should match
// service_traits::MD5Sum< ::ros_services::PressureValue >
template<>
struct MD5Sum< ::ros_services::PressureValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::PressureValue >::value();
  }
  static const char* value(const ::ros_services::PressureValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::PressureValueRequest> should match
// service_traits::DataType< ::ros_services::PressureValue >
template<>
struct DataType< ::ros_services::PressureValueRequest>
{
  static const char* value()
  {
    return DataType< ::ros_services::PressureValue >::value();
  }
  static const char* value(const ::ros_services::PressureValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_services::PressureValueResponse> should match
// service_traits::MD5Sum< ::ros_services::PressureValue >
template<>
struct MD5Sum< ::ros_services::PressureValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::PressureValue >::value();
  }
  static const char* value(const ::ros_services::PressureValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::PressureValueResponse> should match
// service_traits::DataType< ::ros_services::PressureValue >
template<>
struct DataType< ::ros_services::PressureValueResponse>
{
  static const char* value()
  {
    return DataType< ::ros_services::PressureValue >::value();
  }
  static const char* value(const ::ros_services::PressureValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_PRESSUREVALUE_H
