// Generated by gencpp from file ros_services/SonarValue.msg
// DO NOT EDIT!


#ifndef ROS_SERVICES_MESSAGE_SONARVALUE_H
#define ROS_SERVICES_MESSAGE_SONARVALUE_H

#include <ros/service_traits.h>


#include <ros_services/SonarValueRequest.h>
#include <ros_services/SonarValueResponse.h>


namespace ros_services
{

struct SonarValue
{

typedef SonarValueRequest Request;
typedef SonarValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SonarValue
} // namespace ros_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_services::SonarValue > {
  static const char* value()
  {
    return "531b870d85b27f9cb775cebf182532b1";
  }

  static const char* value(const ::ros_services::SonarValue&) { return value(); }
};

template<>
struct DataType< ::ros_services::SonarValue > {
  static const char* value()
  {
    return "ros_services/SonarValue";
  }

  static const char* value(const ::ros_services::SonarValue&) { return value(); }
};


// service_traits::MD5Sum< ::ros_services::SonarValueRequest> should match
// service_traits::MD5Sum< ::ros_services::SonarValue >
template<>
struct MD5Sum< ::ros_services::SonarValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::SonarValue >::value();
  }
  static const char* value(const ::ros_services::SonarValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::SonarValueRequest> should match
// service_traits::DataType< ::ros_services::SonarValue >
template<>
struct DataType< ::ros_services::SonarValueRequest>
{
  static const char* value()
  {
    return DataType< ::ros_services::SonarValue >::value();
  }
  static const char* value(const ::ros_services::SonarValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_services::SonarValueResponse> should match
// service_traits::MD5Sum< ::ros_services::SonarValue >
template<>
struct MD5Sum< ::ros_services::SonarValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_services::SonarValue >::value();
  }
  static const char* value(const ::ros_services::SonarValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_services::SonarValueResponse> should match
// service_traits::DataType< ::ros_services::SonarValue >
template<>
struct DataType< ::ros_services::SonarValueResponse>
{
  static const char* value()
  {
    return DataType< ::ros_services::SonarValue >::value();
  }
  static const char* value(const ::ros_services::SonarValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SERVICES_MESSAGE_SONARVALUE_H
