set(_CATKIN_CURRENT_PACKAGE "demo_teleop")
set(demo_teleop_VERSION "0.0.0")
set(demo_teleop_MAINTAINER "fishy <fishy@todo.todo>")
set(demo_teleop_PACKAGE_FORMAT "2")
set(demo_teleop_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport")
set(demo_teleop_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport")
set(demo_teleop_BUILDTOOL_DEPENDS "catkin")
set(demo_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(demo_teleop_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_runtime")
set(demo_teleop_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_runtime")
set(demo_teleop_TEST_DEPENDS )
set(demo_teleop_DOC_DEPENDS )
set(demo_teleop_URL_WEBSITE "")
set(demo_teleop_URL_BUGTRACKER "")
set(demo_teleop_URL_REPOSITORY "")
set(demo_teleop_DEPRECATED "")